name: Build and Upload JS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare workspace
        run: mkdir -p .github/workflows

      - name: Download origin.js
        run: |
          DEST=".github/workflows/origin.js"
          RAW_MAIN="https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js"
          echo "Downloading origin.js from $RAW_MAIN"
          if ! wget -q -O "$DEST" --tries=3 --timeout=30 "$RAW_MAIN"; then
            echo "// Placeholder origin.js" > "$DEST"
          fi

      - name: Install obfuscator
        run: npm install -g javascript-obfuscator

      - name: Obfuscate origin.js -> works.js
        run: |
          javascript-obfuscator .github/workflows/origin.js \
            --output .github/workflows/works.js \
            --compact true \
            --control-flow-flattening true

      - name: Upload JS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: origin-and-works
          path: |
            .github/workflows/origin.js
            .github/workflows/works.js
