name: Build and Upload JS

on:
  push:
    branches:
      - main

jobs:
  build-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          ORIGIN_URL="https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js"
          OUTPUT_DIR=".github/workflows"

      - name: Download origin.js
        run: |
          mkdir -p $OUTPUT_DIR
          wget -O $OUTPUT_DIR/origin.js $ORIGIN_URL

      - name: Create second JS file
        run: |
          cp $OUTPUT_DIR/origin.js $OUTPUT_DIR/obfuscated.js

      - name: List generated files
        run: |
          ls -l $OUTPUT_DIR
