name: Fetch + Obfuscate -> works.js (one-shot, safe)

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fetch-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Prepare workspace
        run: |
          mkdir -p .github/workflows
          echo "OUTPUT_DIR=.github/workflows" >> $GITHUB_ENV

      - name: Obtain origin.js (with fallback)
        run: |
          REPO="bia-pain-bache/BPB-Worker-Panel"
          DEST=".github/workflows/origin.js"
          TMPDIR="$(mktemp -d)"
          RAW_MAIN="https://raw.githubusercontent.com/${REPO}/main/build/unobfuscated-worker.js"
          echo "Trying to download $RAW_MAIN"
          if ! wget -q -O "$DEST" --tries=3 --timeout=30 "$RAW_MAIN"; then
            echo "// Placeholder origin.js" > "$DEST"
          fi

      - name: Install javascript-obfuscator
        run: npm install -g javascript-obfuscator

      - name: Obfuscate origin.js -> works.js
        run: |
          javascript-obfuscator .github/workflows/origin.js \
            --output .github/workflows/works.js \
            --compact true \
            --control-flow-flattening true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: origin-and-works
          path: |
            .github/workflows/origin.js
            .github/workflows/works.js
